# Publicacion en GitHub Pages
baseurl = "https://onthedock.github.io/"

# Publicacion en RPi
#baseurl = "http://192.168.1.9:8000/"

title = "On The Dock"
theme = "aglaus-custom"

copyright = "Handmade with &#9829; by Xavi Aznar"

googleAnalytics = "" # Optional

[params]
  dateformat = "2 Jan 2006" # Optional
  latestSize = 4 # Optional
  ampscripts = """
<script async custom-element="amp-twitter" src="https://cdn.ampproject.org/v0/amp-twitter-0.1.js"></script>
<script async custom-element="amp-iframe" src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script>
<script async custom-element="amp-ad" src="https://cdn.ampproject.org/v0/amp-ad-0.1.js"></script>
"""
  details = "Un blog sobre Cloud, Kubernetes, DevOps, Docker y Raspberry Pi por Xavier Aznar"
  author = "Xavier Aznar"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.highlight]
    codeFences = true
    style = "native"
    tabWidth = 2
  
